In [2]:
import pandas as pd
import numpy as np

In [6]:
mt=pd.read_csv("./density/metrics_table_0.csv")

In [2]:
def read_file(url):

    url = url + "?raw=true"
    df = pd.read_csv(url, encoding='cp1252', sep=',', low_memory=False)
    return df

In [9]:
mt.iloc[:,1:].iloc[[0, 25, 50, 100, 250, 500, 750, 1000, 2500, 4000],:]

,accuracy,balanced_accuracy,recall,precision,auc,pr_auc,f1_score,f2_score,log_loss
0,0.945833,0.772140,0.560748,0.769231,0.772140,0.684573,0.648649,0.592885,1.870862
25,0.952500,0.780015,0.570093,0.847222,0.780015,0.727825,0.681564,0.610000,1.640599
50,0.954167,0.785145,0.579439,0.861111,0.785145,0.739025,0.692737,0.620000,1.583034
100,0.960833,0.814097,0.635514,0.894737,0.814097,0.781375,0.743169,0.674603,1.352774
250,0.975000,0.889321,0.785047,0.923077,0.889321,0.863645,0.848485,0.809249,0.863474
500,0.976667,0.890236,0.785047,0.943820,0.890236,0.874017,0.857143,0.812379,0.805908
750,0.983333,0.919188,0.841121,0.967742,0.919188,0.911515,0.900000,0.863724,0.575648
1000,0.980833,0.905170,0.813084,0.966667,0.905170,0.898209,0.883249,0.839768,0.661995
2500,0.977500,0.903340,0.813084,0.925532,0.903340,0.877641,0.865672,0.833333,0.777127
4000,0.974167,0.888864,0.785047,0.913043,0.888864,0.858628,0.844221,0.807692,0.892257

In [ ]:
mt_combined=

In [3]:
def create_CI_table(iterations, queried_instances, queried_instances_uncertainty):
for i in iterations:
    mt_d= pd.read_csv("./density/metrics_table_{}.csv".format(num))
    mt_u= pd.read_csv("./uncertainty/metrics_table_{}.csv".format(num))
            df_queried_d=df_train.iloc[list(queried_instances.iloc[:i,1])]
            df_queried_d_pos=df_queried_d.loc[df_queried_d['y_10']==1].shape[0]
            pos_queried_d.append(df_queried_d_pos/i)
            pos_sample_d.append((df_queried_d_pos+sample_init_pos.shape[0])/(i+sample_init.shape[0]))
            df_queried_u=df_train.iloc[list(queried_instances_uncertainty.iloc[:i,1])]
            df_queried_u_pos=df_queried_u.loc[df_queried_u['y_10']==1].shape[0]
            pos_queried_u.append(df_queried_u_pos/i)
            pos_sample_u.append((df_queried_u_pos+sample_init_pos.shape[0])/(i+sample_init.shape[0]))

    # assign data of lists.  
    data = {'i': iterations
            , '%_queried_d': pos_queried_d
            , '%_queried_u': pos_queried_u
            , '%_sample_d': pos_sample_d
            , '%_sample_u': pos_sample_u}  
    return pd.DataFrame(data)

In [4]:
iterations=[0, 25, 50, 100, 250, 500, 750, 1000, 2500, 4000]
tables=[]

for num in range(10):
    mt=
    CI_table=create_CI_table(iterations, queried_instances, queried_instances_uncertainty)  
    print(CI_table)
    tables.append(CI_table)

    
df_tables = pd.concat(tables)
mean_table = df_tables.groupby(level=0).mean()
print(mean_table)

      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0      0.00000     0.000000    0.188742    0.188742
1    25      0.52000     0.320000    0.214067    0.198777
2    50      0.50000     0.400000    0.232955    0.218750
3   100      0.54000     0.540000    0.276119    0.276119
4   250      0.49200     0.520000    0.326087    0.338768
5   500      0.40200     0.538000    0.321696    0.406484
6   750      0.36000     0.517333    0.310837    0.423004
7  1000      0.33600     0.502000    0.301843    0.429339
8  2500      0.24200     0.318400    0.236260    0.304425
9  4000      0.19525     0.233000    0.194793    0.229893
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0      0.00000     0.000000    0.182119    0.182119
1    25      0.48000     0.480000    0.204893    0.204893
2    50      0.60000     0.500000    0.241477    0.227273
3   100      0.52000     0.520000    0.266169    0.266169
4   250      0.50000     0.568000    0.326087    0.356884
5   500      0.40800     0.538000    0.322943    0.403990
6   750      0.37600     0.513333    0.320342    0.418251
7  1000      0.34300     0.490000    0.305684    0.418587
8  2500      0.24800     0.311600    0.240899    0.297645
9  4000      0.19875     0.228250    0.197583    0.225012
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0     0.000000     0.000000    0.211921    0.211921
1    25     0.600000     0.400000    0.241590    0.226300
2    50     0.560000     0.480000    0.261364    0.250000
3   100     0.500000     0.550000    0.283582    0.296020
4   250     0.416000     0.488000    0.304348    0.336957
5   500     0.374000     0.498000    0.312968    0.390274
6   750     0.345333     0.502667    0.307034    0.419202
7  1000     0.326000     0.478000    0.299539    0.416283
8  2500     0.238800     0.309600    0.235903    0.299072
9  4000     0.195250     0.230750    0.196420    0.229428
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0     0.000000     0.000000    0.178808    0.178808
1    25     0.520000     0.560000    0.204893    0.207951
2    50     0.580000     0.500000    0.235795    0.224432
3   100     0.610000     0.560000    0.286070    0.273632
4   250     0.508000     0.556000    0.327899    0.349638
5   500     0.416000     0.526000    0.326683    0.395262
6   750     0.374667     0.509333    0.318441    0.414449
7  1000     0.345000     0.495000    0.306452    0.421659
8  2500     0.249600     0.312400    0.241970    0.298001
9  4000     0.197250     0.232500    0.195955    0.228731
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0     0.000000       0.0000    0.162252    0.162252
1    25     0.560000       0.4000    0.192661    0.180428
2    50     0.560000       0.4600    0.218750    0.204545
3   100     0.550000       0.5800    0.258706    0.266169
4   250     0.508000       0.5640    0.318841    0.344203
5   500     0.408000       0.5440    0.315461    0.400249
6   750     0.369333       0.5240    0.309886    0.420152
7  1000     0.345000       0.5070    0.302611    0.427035
8  2500     0.254800       0.3084    0.244825    0.292648
9  4000     0.201000       0.2320    0.198280    0.227104
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0      0.00000      0.00000    0.149007    0.149007
1    25      0.56000      0.56000    0.180428    0.180428
2    50      0.62000      0.60000    0.215909    0.213068
3   100      0.64000      0.61000    0.271144    0.263682
4   250      0.54400      0.58400    0.327899    0.346014
5   500      0.45000      0.55600    0.336658    0.402743
6   750      0.38800      0.53200    0.319392    0.422053
7  1000      0.35500      0.51200    0.307220    0.427803
8  2500      0.25280      0.31840    0.241613    0.300143
9  4000      0.19875      0.22975    0.195258    0.224082
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0       0.0000     0.000000    0.188742    0.188742
1    25       0.4400     0.400000    0.207951    0.204893
2    50       0.4200     0.500000    0.221591    0.232955
3   100       0.5200     0.500000    0.271144    0.266169
4   250       0.4440     0.520000    0.304348    0.338768
5   500       0.3840     0.508000    0.310474    0.387781
6   750       0.3520     0.497333    0.305133    0.408745
7  1000       0.3310     0.482000    0.298003    0.413978
8  2500       0.2420     0.306400    0.236260    0.293719
9  4000       0.1945     0.224250    0.194096    0.221757
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0     0.000000     0.000000    0.168874    0.168874
1    25     0.640000     0.720000    0.204893    0.211009
2    50     0.600000     0.640000    0.230114    0.235795
3   100     0.580000     0.600000    0.271144    0.276119
4   250     0.484000     0.536000    0.311594    0.335145
5   500     0.404000     0.536000    0.315461    0.397756
6   750     0.374667     0.514667    0.315589    0.415399
7  1000     0.347000     0.491000    0.305684    0.416283
8  2500     0.252400     0.311600    0.243398    0.296217
9  4000     0.202750     0.228250    0.200372    0.224082
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0       0.0000     0.000000    0.158940    0.158940
1    25       0.5200     0.440000    0.186544    0.180428
2    50       0.6000     0.480000    0.221591    0.204545
3   100       0.5900     0.500000    0.266169    0.243781
4   250       0.5000     0.552000    0.313406    0.336957
5   500       0.4120     0.546000    0.316708    0.400249
6   750       0.3680     0.530667    0.307985    0.423954
7  1000       0.3430     0.500000    0.300307    0.420891
8  2500       0.2468     0.310400    0.237330    0.294076
9  4000       0.1975     0.230000    0.194793    0.225012
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0     0.000000     0.000000    0.218543    0.218543
1    25     0.440000     0.160000    0.235474    0.214067
2    50     0.520000     0.320000    0.261364    0.232955
3   100     0.500000     0.480000    0.288557    0.283582
4   250     0.488000     0.468000    0.340580    0.331522
5   500     0.392000     0.492000    0.326683    0.389027
6   750     0.345333     0.481333    0.308935    0.405894
7  1000     0.322000     0.478000    0.298003    0.417819
8  2500     0.241200     0.307200    0.238758    0.297645
9  4000     0.193250     0.227250    0.195026    0.226639
      i  %_queried_d  %_queried_u  %_sample_d  %_sample_u
0     0     0.000000     0.000000    0.180795    0.180795
1    25     0.528000     0.444000    0.207339    0.200917
2    50     0.556000     0.488000    0.234091    0.224432
3   100     0.555000     0.544000    0.273881    0.271144
4   250     0.488400     0.535600    0.320109    0.341486
5   500     0.405000     0.528200    0.320574    0.397382
6   750     0.365333     0.512267    0.312357    0.417110
7  1000     0.339300     0.493500    0.302535    0.420968
8  2500     0.246840     0.311440    0.239722    0.297359
9  4000     0.197425     0.229600    0.196258    0.226174

In [5]:
mean_table.to_csv('b1_CI_table.csv')