In [2]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df_reduced=pd.read_csv('dielectron_reduced_noise_classes.csv')

In [3]:
fold_test=pd.read_csv('test_{}.csv'.format(1))

In [7]:
fold_test.head()

,Run,Event,E1,px1,py1,pz1,pt1,eta1,phi1,Q1,...,eta2,phi2,Q2,M,M_noise,y_50,y_25,y_10,index_reduced,index_og
0,147115,119132977,6.27527,-1.80276,-2.08176,-5.63874,2.75385,-1.464710,-2.28449,-1,...,-2.39455,1.154500,1,15.1072,8.289502,False,False,False,3,3056
1,146644,1625276307,18.06410,-13.65140,-11.47990,2.85751,17.83670,0.159527,-2.44239,1,...,-1.59647,-1.781340,-1,16.7522,14.247313,False,False,False,8,17257
2,149181,992365413,40.38860,3.47109,34.93820,-19.96280,35.11020,-0.541693,1.47177,-1,...,-1.70616,-1.967200,1,23.8009,19.553967,False,False,False,34,29821
3,149181,1653195519,119.00800,-25.08100,34.98980,110.94900,43.05050,1.675520,2.19271,1,...,1.46314,-0.890383,-1,32.5112,30.469155,True,False,False,43,27086
4,146644,1486682862,7.69058,1.25048,2.09834,7.29234,2.44269,1.813810,1.03337,-1,...,-2.18271,-0.572436,-1,24.3584,22.769651,True,False,False,51,12963

In [6]:
fold_test=fold_test.iloc[:,1:]

In [9]:
for i in range(20):
    fold_test=pd.read_csv('test_{}.csv'.format(i))
    fold_test=fold_test.iloc[:,1:]
    fold_test.to_csv('test_{}.csv'.format(i), index=False)